title: Gourlaysama's blog
subtitle: Documenting musings and mistakes
author: Antoine Gourlay
simple_search: http://google.com/search
description: My blog
name: gourlaysama-blog
permalink: /articles/:short_year/:title
timezone: Europe/Paris
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: local