title: Gourlaysama's blog
subtitle: Documenting musings and mistakes
author: Antoine Gourlay
simple_search: http://google.com/search
description: My blog
name: gourlaysama-blog
permalink: /:slugified_categories/:short_year/:slug
timezone: Europe/Paris
excerpt_separator: <!--more-->
url: "https://gourlaysama.github.io"
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "publish_local.sh"
  ]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: code
git:
  branch: local
kramdown:
  math_engine: katex